const { IPC } = require('../../lib/ipc-channels');

module.exports = {
  id: 'audio',
  version: '1.0.0',
  channels: [
    IPC.AUDIO_GET_DEVICES,
    IPC.AUDIO_START_RECORDING,
    IPC.AUDIO_STOP_RECORDING,
    IPC.AUDIO_PAUSE_RECORDING,
    IPC.AUDIO_RESUME_RECORDING,
    IPC.AUDIO_GET_RECORDING_STATUS,
    IPC.AUDIO_ON_TRANSCRIPTION_UPDATE,
    IPC.AUDIO_ON_TRANSCRIPTION_CORRECTION,
    IPC.AUDIO_ON_RECORDING_STATUS,
    IPC.AUDIO_ON_LEVELS,
    IPC.AUDIO_ON_SPEAKER_LABELS
  ]
};
